table:
  schema_name: public
  name: film
  target_schema_name: raw
  target_name: pagila_film

source:
  type: postgresql
  runtime: pagila_postgres_database
  query_path: film.sql

target:
  type: local
  runtime: development_storage

replication:
  mode: full_load
  partition:
    type: year
    reference_column: last_update
