table:
  schema_name: public
  name: actor
  target_schema_name: raw
  target_name: pagila_actor

source:
  type: postgresql
  runtime: pagila_postgres_database

target:
  type: local
  runtime: development_storage

replication:
  mode: full_load
