table:
  schema_name: public
  name: comments
  target_schema_name: raw
  target_name: stackoverflow_comments

source:
  type: postgresql
  runtime: stackoverflow_postgres_database
  chunk_size: 50000

target:
  type: local
  runtime: development_storage
  chunk_size: 200000

replication:
  mode: incremental
  strategy:
    type: replace
    reference_column: creationdate
    lookback_periods: 19
    partition:
      type: year
